version: '3.7'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  db-integration-tests:
    image: mysql:8.0
    container_name: mysql-integration-tests
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: todo_db_integration
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      DATASOURCES_DEFAULT_URL: jdbc:mysql://db:3306/todo_db
      DATASOURCES_DEFAULT_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      DATASOURCES_DEFAULT_USERNAME: user
      DATASOURCES_DEFAULT_PASSWORD: password
